### ISSUE TITLE
branch: healing | No Switch Loop

### ISSUE THREAD

**Issue by BellBot123** [M1L4/QuestingDebug#1]
Steel Mangetbull example:
when bot leveling lowest pokemon in the party it tries to switch out the higher level pokemon but sometime it face with some pokemon that cant run away it stuck( example:rt6)
log info:
[6:52:58 AM] A Wild Magnemite Attacks!
[6:53:03 AM] You can not switch this Pokemon!
[6:53:06 AM] You can not switch this Pokemon!
...

**Comment by M1L4** [comment]
Should have already been fixed, I added all battle related debug prints. If encountered again, pls post them here.

**Comment by M1L4** [comment]
@BellBot123 From the Log I get you are having the resource folder installed. I didn't know there exists one until recently, so my battleMessage catches are the actual MessageIds: $No_Run and $No_Switch instead of some the dialogs. I'll update it right away, give me feedback, if it's working.

As usual, reopen if you encounter the error again :)
