### ISSUE TITLE
branch: bikeQuest | Gym 6

### ISSUE THREAD

**Issue by BellBot123** [M1L4/QuestingDebug#3]
after it defeat gym 6 it didn't move to cinnabar island for some reason until i am manually move it near the beach so it can surf to cinnabar island(edited)

**Comment by M1L4** [comment]
I splitted the original issue. The other part is #16 *branch: bikeQuest | seafoam island nurse loop, when one pkm can't level up*

**Comment by M1L4** [comment]
What did it do instead? 
My Personal Encounter was:
1. originally a loose in the gym wasn't considered, so the bot would endlessly try to fight sabrina. I added a training method for Route 8, since it is the closest. 
2. skipping the _ExpForSaffronQuest_ - this happens when moving out of that _ExpForSaffronQuest_'s "scanned" areas. Should be from Route 19 to Seafoam Island or Cinnabar Pokecenter. 
    - when that happens the bot starts the _SaffronGuardQuest_ and would travel to saffron
    - skipping _ExpForSaffronQuest_, would lead to a major level difference. Instead of leveling 1 level (from 60 to 61, after next loose 62, ....) you have to level around 20-30 lvls, which is in that underleveled zone quite troublesome. 

Is this what you experienced as well?

**Comment by M1L4** [comment]
Since you didn't comment, I assume that the uploaded fixes are sufficient :)
Reopen if not ;)
