### ISSUE TITLE
branch: GoldenrodLeverPuzzle | Can't find oddish in boxes

### ISSUE THREAD

**Issue by 0x526f6d656f** [M1L4/QuestingDebug#31]
Got 10+ boxes full of Oddish, can't find a single one.
After putting Oddish into the team, it proceeds to level the Oddish up. (not sure if that's because of the quest min level or because of oddish needing a certain level)

**Comment by M1L4** [comment]
Because it isn't searching for a oddish at all :)

In regards to #13 suggestion of catching bellsprout instead of oddish, will the pc be checked for bellsprout and no longer searching for an oddish.
The new quest progression is as follows:
- catching bellsprout on route 32:
    - we won't loose much time, since we already were leveling here for quite some time without catching it
- after catching bellsprout, we retrieve it in violet city or the pokecenter on route 32
    - we do this, so we can level bellsprout from ~6 to 13, when it learns SleepPowder. It is so we can avoid the extra leveling time in goldenrod city for a new sleep powderer
- when reaching goldenrod all should be done already

It seems to me as if you changed commits midway:
- skipping part 1 catching bellsprout with an older commit, but
- expecting one now with one of the more recent commits

3 solution ideas:
- You can either revert back to your previous commit (or use master) at which point it will use the oddish in you box.
- if the script recognizes ZephyQuest to be still doable: then you could go back to route 32 and let the script work it's magic again. Most probably it will tell you though, that all Quests are completed.
- sleep powder the guard yourself, go to the basement and start the script from there

**Comment by prouser1234** [comment]
so another problems with bellsprout. it is not spawn during night and i passed that route, what to do?
