### ISSUE TITLE
branch: master | gym 6

### ISSUE THREAD

**Issue by BellBot123** [M1L4/QuestingDebug#6]
when the bot losing a 6 gym, and it want to leveling on rt 8, after it reach the level the bot will stop at stop house when it moving back to safforn city. go through safe house manually seem to fix the problem.

**Comment by M1L4** [comment]
For future reference: could you provide more detailed information?
- running quest
- gym/city or badge names (since order can be altered, at least in the original games)
- Exception or Debug log, when possible and related. Post it if you are unsure.

I fixed it, could you tell me if it works as inteded? I don't have bots with that progression state atm...
